### ISSUE TITLE
initial checklist

### ISSUE THREAD

**Issue by deads2k** [openshift/cluster-config-operator#3]
- [x] verify
- [x] images
- [x] test-aws
- [x] unit
- [x] merge bot
- [ ] render command without a destination config
- [ ] render command get access to config structs we have
- [ ] render command that doesn't panic and kind of works
- [x] OCP images: https://mojo.redhat.com/docs/DOC-1178565#jive_content_id_How_can_I_get_ART_to_build_a_new_image_for_my_team

@tnozicka

**Comment by tnozicka** [comment]
first 5 should be covered by https://github.com/openshift/release/pull/2541

**Comment by tnozicka** [comment]
when that merges I'm gonna look into the ART process

**Comment by tnozicka** [comment]
ocp images in progress https://jira.coreos.com/browse/ART-449

**Comment by tnozicka** [comment]
@deads2k I think I've already pinged you with it, but we should officially have the OCP image
